# https://docs.docker.com/reference/compose-file/version-and-name/#name-top-level-element
name: testapp

# https://docs.docker.com/reference/compose-file/services/
services:
  test:
    build:
      dockerfile_inline: |
        FROM node:alpine
        WORKDIR /app
        COPY . .
        RUN ls
    entrypoint: "node"
    command: "demo"
    tty: true
    user: node
    # `init: true` is generally required by Node applications because Node does not behave well
    # when it is PID 1
    # Source: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    init: true
    environment:
      HOST: localhost
      PORT: 80
      FRONTEND: http://localhost:8080
    ports:
      - "8080:80"
    secrets:
      - source: sec1
        target: "/app/secrets/sec1"
    develop:
      watch:
        - path: .
          action: sync+restart
          target: ./app

secrets:
  sec1:
    file: secrets