name: ViteDemo

# Note that when using compose extend to define services that 
# inherit secrets mapping, the secrets must be defined in the main
# compose file, not the common compose file that defines the base
# service that consumes the secrets.
secrets:
  secrets1:
    file: ./back/secrets.json

services:
  dev-front:
    profiles:
      - dev
    depends_on:
      - dev-back
    extends:
      file: ./common.yaml
      service: front-base
    build:
      target: dev-stage
    develop:
      watch:
        - path: ./front/src
          action: sync
          target: /app/src
        - path: ./front/package.json
          action: rebuild
    # Start Vite's hot module replacement function
    command: ["yarn", "dev"]

  prd-front:
    profiles:
      - prd
    depends_on:
      - prd-back
    extends:
      file: ./common.yaml
      service: front-base
    build:
      # Override extended base service attribute
      args:
        VITE_HOST: localhost
    # It is assumed that the final image in the Dockerfile
    # has Node's http-server package installed globally
    command: ["http-server"]

  dev-back:
    profiles:
      - dev
    extends:
      file: ./common.yaml
      service: back-base
    ports:
      - "8081:8080"
    build:
      args:
        VITE_HOST: 0.0.0.0
        VITE_PORT: 8080
      target: dev-stage
    develop:
      watch:
        - path: ./back/src
          action: sync
          target: /app/src
        - path: ./back/package.json
          action: rebuild
    command: ["yarn", "dev"]

  prd-back:
    profiles:
      - prd
    extends:
      file: ./common.yaml
      service: back-base
    # For some reason, the ports between the host and the
    # container need to match in production.
    ports:
      - "8081:8081"
    build:
      target: server

  hc-back:
    profiles:
      - hc
    extends:
      file: ./common.yaml
      service: back-base
    ports:
      - "8081:8081"
    healthcheck:
      test:
       - CMD-SHELL
       - >-
         curl -f
         --url http://localhost:8081/secrets
         --request POST
         --header 'Content-Type: application/json'
         --header 'Referer: http://localhost:8080'
         --data "{\"name\": \"SECRET\"}"
         || exit 1
      interval: 5s
      timeout: 10s
      retries: 2
      start_period: 10s